let mySprite = sprites.create(assets.image`Aran`, SpriteKind.Player)
scene.setBackgroundColor(7)
mySprite.setPosition(80, 60)
mySprite.setVelocity(50, 0)
controller.moveSprite(mySprite)
let Sprite_2 = sprites.create(assets.image`Hugo`, SpriteKind.Player)
mySprite.setPosition(0, 0)
controller.moveSprite(mySprite, 100, 100)
Sprite_2.follow(mySprite, 60)
